name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types:
      - fast-forward

jobs:
  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install pytest
      - run: pytest -s -vv --log-cli-level=DEBUG --disable-warnings .
